SPAメモアプリの作成
ksmxxxxxx/note_app_with_vue pull request #3
Opened 2021-04-15 12:06 UTC by ksmxxxxxx

VueCLIでメモアプリを作成しました。

必須要件にはなかったのですが、vue-routerをつかってページングするようにしています。

作業記録として #1 と #2 があります。

## 環境

- VueCLI @vue/cli 4.5.12
- Vue 3.0.10
- vue-router  4.0.5
- Node: 14.16.0
- Yarn: 1.22.10
- npm: 6.14.11

## Usage
```
yarn install

yarn serve
```

# レビューがほしいポイント
- コンポーネントの命名
- コンポーネントファイルの構成など

### Screenshot

![Apr-15-2021 20-50-37](https://user-images.githubusercontent.com/5976902/114866131-287e9280-9e2e-11eb-808a-0e45c130105c.gif)
![Apr-15-2021 20-51-01](https://user-images.githubusercontent.com/5976902/114866161-32a09100-9e2e-11eb-90b4-830e9e71aa34.gif)
![Apr-15-2021 20-51-18](https://user-images.githubusercontent.com/5976902/114866180-37fddb80-9e2e-11eb-924b-cc01e6325b3d.gif)

2021-04-22 00:49 UTC, komagata commented
> コンポーネントの命名
> コンポーネントファイルの構成など

今ので良いと思います〜

> 編集のフォーム部分、タイトルを空（nullではなく "" ）の状態で保存できてしまうのは、アプリとしてよろしくないなぁと思って、修正しようと試みましたがどうしても自力での解決ができなかったのでそのままにしました。

bindingの名前、`newNote.body`みたいにできるんですかね？（僕やったことないので知りませんでした。）

```
      newNote: {
        title: null,
        body: null,
        edit: false
      },
```

新規のnoteのフォームはこう言う構造じゃなくて

```
title: null,
body: null,
edit: false
```

みたいな感じでやったらどうかな〜と思いました。

2021-04-23 11:03 UTC, ksmxxxxxx commented
> > コンポーネントの命名
> > コンポーネントファイルの構成など
> 
> 今ので良いと思います〜
> 
> > 編集のフォーム部分、タイトルを空（nullではなく "" ）の状態で保存できてしまうのは、アプリとしてよろしくないなぁと思って、修正しようと試みましたがどうしても自力での解決ができなかったのでそのままにしました。
> 
> bindingの名前、`newNote.body`みたいにできるんですかね？（僕やったことないので知りませんでした。）
> 
> ```
>       newNote: {
>         title: null,
>         body: null,
>         edit: false
>       },
> ```
> 
> 新規のnoteのフォームはこう言う構造じゃなくて
> 
> ```
> title: null,
> body: null,
> edit: false
> ```
> 
> みたいな感じでやったらどうかな〜と思いました。

@komagata 

https://github.com/ksmxxxxxx/note_app_with_vue/pull/3/commits/2f17389c630c810ae3078f29c553230f4a1d4a81
コメントを参考に修正してみました。
ただ、質問タイムでも聞いたんですが、結局methodのところでハッシュにしてlocalStorageに保存するので、この構造にするメリットがあまり感じられないです 🤔 

また、ハッシュにするとバインディングができないんじゃないかということでしたが、自分で手元で確認してみましたがハッシュにしてもバインディングはできるように見えます。
なので、余計におっしゃられた構造にしたほうが良いというのが飲み込めませんでした😢

↓雑に試してみたバインディングのコードです
https://codesandbox.io/s/v-modelbinding-sr9ed?file=/src/App.vue

2021-04-24 02:48 UTC, ksmxxxxxx commented
@komagata 

8a259d1058e9504d3517f3b1e5fd80e735385f8b

NoteDetail.vueでやりたかったことは以下です。

- メモのタイトルが空になったらSaveボタンに`disabled`属性が有効になる
- そのため、メモのタイトルの入力部分（`<input type="text" v-model="this.notes[this.$props.id].title" class="mb-2">`）を`watch`して、`input`が空になったら`disabled`を`true`、`input`になにか入力されれば`disabled`を`false`にするという関数（`activateSave ()`）が走るようにしたかった

commitの中でコメントに残っているのはwatchできるかをデバックしていた痕跡として残しています。


こうしようかなと思っていることも書いておきます。

- まずlocalStorageに登録しているデータを全部コンポーネントに入れている状態なので、必要なものだけをコンポーネントに入れるに変更する
- 必要なメモのデータだけもつようにすれば、`this.$props.id`を使わなくても良くなる……はず。

これまでに参考にしたドキュメント
https://v3.ja.vuejs.org/api/options-data.html#watch
https://v3.ja.vuejs.org/api/instance-methods.html#watch
https://v3.ja.vuejs.org/guide/computed.html
https://v3.ja.vuejs.org/guide/computed.html#%E3%82%A6%E3%82%A9%E3%83%83%E3%83%81%E3%83%A3
https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html#%E7%AE%97%E5%87%BA%E3%83%95%E3%82%9A%E3%83%AD%E3%83%8F%E3%82%9A%E3%83%86%E3%82%A3

2021-04-24 11:22 UTC, ksmxxxxxx commented
@komagata 

https://github.com/ksmxxxxxx/note_app_with_vue/pull/3/commits/1a51ce5d36124eef45f4d3159eee85511419ce1c

編集画面において、タイトルの入力欄がからの場合はSaveボタンをdisabledになる（保存できない）commitを追加しました。

2021-04-24 16:36 UTC, komagata requested changes

2021-04-24 16:36 UTC, komagata commented on src/components/NoteAddForm.vue
>        this.notes.push(this.newNote)
この`notes`と`newNote`はこのコンポーネント内のどこかで表示されているわけではないので
コンポーネントの`data`にする必要はないかもです。

特に`newNote`は`title`, `body`などが既にあるのでそちらを使えば良いと思います。

`notes`もlocalStorageに保存するだけだったら不要だと思います。

2021-04-25 14:26 UTC, ksmxxxxxx commented on src/components/NoteAddForm.vue
>        this.notes.push(this.newNote)
ありがとうございます。

425e91e
こちらに調整したcommitを追加しました。

2021-04-26 08:17 UTC, komagata requested changes

2021-04-26 08:17 UTC, komagata commented on src/components/NoteAddForm.vue
> +      if (this.title) {
一度しか出てこないならメソッドにしなくてもいいかも？

2021-04-26 08:17 UTC, komagata commented on src/components/NoteAddForm.vue
> +    cancelAdd () {
cancelAdd -> cancel
saveNote -> save

とかの方が他の人から見てわかりやすいかもです〜

2021-04-26 14:33 UTC, ksmxxxxxx commented on src/components/NoteAddForm.vue
> +      if (this.title) {
Fixed 
51b160e

2021-04-26 14:34 UTC, ksmxxxxxx commented on src/components/NoteAddForm.vue
> +    cancelAdd () {
Fixed

9963bd6

2021-04-27 08:22 UTC, komagata requested changes

2021-04-27 08:22 UTC, komagata commented on src/components/NoteDetail.vue
> +      notes: [],
NoteDetalは一つのNoteに関するcomponentだと思うので、`note`をこのコンポーネントに渡してあげればそれで良いかもです。（スコープを絞ってなるべく最小限のデータを渡すのが望ましいので）

2021-04-27 08:22 UTC, komagata commented on src/components/NoteDetail.vue
>      deleteNote () {
これらもcomponent名がNoteDetailということは一つのnoteが主語に限定されているので、`delete` `cancel`などの方が簡潔で分かりやすいと思います〜

2021-04-27 15:17 UTC, ksmxxxxxx commented on src/components/NoteDetail.vue
>      deleteNote () {
変更のcommitを追加しました 🙏🏻 
b9d499e

2021-04-27 18:33 UTC, komagata approved these changes
確認しました。OKです～！

2021-06-30 10:53 UTC, merged